name: Publish
on:
  push:
    tags:
      - v*
permissions:
  id-token: write
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: npm
    name: Publish
    steps:
      - uses: holepunchto/actions/node-base@aec0d5d8fb4e5b9c2480f79cd687db941428a279 # v1
      - uses: holepunchto/actions/publish@aec0d5d8fb4e5b9c2480f79cd687db941428a279 # v1
